name: Deploy to GitHub Pages

on:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled, transferred]
  issue_comment:
    types: [created, deleted]
  discussion:
    types: [created, edited, deleted, transferred, category_changed, labeled, unlabeled]
  discussion_comment:
    types: [created, deleted]
  label:
    types: [edited, deleted]
  workflow_dispatch:

jobs:
  deploy:
    uses: zeikar/atcoder/.github/workflows/deploy.yml@repozine
    permissions:
      contents: read
      issues: read
      discussions: read
      pages: write
      id-token: write
